#!/usr/bin/env sh

# Wraps symlinks of the form e<cmd> to ecmd <cmd>
_basecmd="$(basename "$0")"
_cmd="${_basecmd#e}"

if [ "$_cmd" = "$_basecmd" ]; then
    echo "Invalid invocation, $_basecmd is not a symlink or invalid" >&2
    exit 1
fi

ecmd "$_cmd" "$@"
