#!/usr/bin/env sh

# Outputs command with arguments to stdout (which can be redirected to a file)
# This can be used to get a log of commands like cp rm and mv which can be used
# to reproduce changes accross a network (I haven't yet tested this); however
# the output is correct with files with spaces and should work for newlines if
# the shell sees it correctly.
#
# Example: ecmd foo "foo bar" >> cmds
# . cmds
# copy this to the remote directory and do the same
# ensure that the subdirectories are the same?
  


_usage() {
cat << EOF
usage: $0 <command> [arguments] 
EOF
}

[ "$#" -lt 1 ] && { _usage ; exit 1;} 

_cmd="$1"; shift 1
# Iterates through arguments and quotes them 
for i in "$@"; do
  ALIST="$ALIST "\""$i"\"
done

printf '%s\n' "$_cmd $ALIST"